---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: snow-workload-2
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 10.1.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: "192.168.1.121"
    machineGroupRef:
      kind: SnowMachineConfig
      name: snow-workload-2-cp
  datacenterRef:
    kind: SnowDatacenterConfig
    name: snow-workload-2
  kubernetesVersion: "1.21"
  managementCluster:
    name: snow-management
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: SnowMachineConfig
      name: snow-workload-2
    name: md-1
  gitOpsRef:
    kind: FluxConfig
    name: snow-workload-2

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: SnowDatacenterConfig
metadata:
  name: snow-workload-2
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: SnowMachineConfig
metadata:
  name: snow-workload-2-cp
  namespace: default
spec:
  amiID: s.ami-eks-d-v1-21-5-ubuntu-ami-2022-03-18
  instanceType: sbe-c.large
  sshKeyName: default
  physicalNetworkConnector: SFP_PLUS

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: SnowMachineConfig
metadata:
  name: snow-workload-2
  namespace: default
spec:
  amiID: s.ami-eks-d-v1-21-5-ubuntu-ami-2022-03-18
  instanceType: sbe-c.large
  sshKeyName: default
  physicalNetworkConnector: SFP_PLUS 

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: snow-workload-2
  namespace: default
spec:
    github:
      personal: true
      repository: eksa-demo
      owner: jiayiwang7

