apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by: docker-management
  name: docker-workload-1
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: docker-workload-1
  gitOpsRef:
    kind: FluxConfig
    name: docker-workload-flux
  kubernetesVersion: "1.22"
  managementCluster:
    name: docker-management
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: docker-workload-1
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: docker-workload-flux
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/docker-management
  github:
    owner: jiayiwang7
    personal: true
    repository: eksa-demo
  systemNamespace: flux-system

---
